version: '3'

services:
  db:
    tty: true
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - valdinet
    volumes:
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=batata
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 10
  node:
    container_name: node
    build:
      context: ./node
    tty: true
    networks:
      - valdinet
    volumes:
      - ./node:/usr/share/app
    depends_on:
      db:
        condition: service_healthy
  nginx:
    container_name: nginx
    tty: true
    build:
      context: ./nginx
    ports:
      - "3000:80"
    networks:
      - valdinet
    depends_on:
      - node

networks:
  valdinet:
    name: valdinet
    driver: bridge
